-- ============================================================================
-- Supabase PostgreSQL Schema for FAFB LP Church Management System
-- ============================================================================
-- Instructions:
-- 1. Open Supabase Dashboard -> Click "SQL Editor" (on the left menu)
-- 2. Click "New query"
-- 3. Copy EVERYTHING in this file, paste into Supabase SQL Editor, and click "RUN"
-- ============================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'viewer',
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Organizations Table
CREATE TABLE IF NOT EXISTS public.organizations (
    "id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "leaderId" TEXT,
    "description" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Members Table
CREATE TABLE IF NOT EXISTS public.members (
    "id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "profileImage" TEXT,
    "family" TEXT,
    "birthdate" TEXT,
    "contact" TEXT,
    "address" TEXT,
    "organizationId" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Ministries Table
CREATE TABLE IF NOT EXISTS public.ministries (
    "id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "datetime" TEXT,
    "description" TEXT,
    "participants" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Pledges & Records Table
CREATE TABLE IF NOT EXISTS public.pledges (
    "id" TEXT PRIMARY KEY,
    "type" TEXT NOT NULL,
    "family" TEXT,
    "memberId" TEXT,
    "eventId" TEXT,
    "amount" NUMERIC(12, 2) DEFAULT 0.00,
    "pledgeAmount" NUMERIC(12, 2) DEFAULT 0.00,
    "paidAmount" NUMERIC(12, 2) DEFAULT 0.00,
    "status" TEXT,
    "pledgeStatus" TEXT,
    "notes" TEXT,
    "thanksgivingDate" TEXT,
    "hospitalName" TEXT,
    "admissionDate" TEXT,
    "dischargeDate" TEXT,
    "groomName" TEXT,
    "brideName" TEXT,
    "weddingDate" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- Grant Schema & Table Permissions to Anonymous / Authenticated Roles
-- ============================================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- ============================================================================
-- Enable Row Level Security (RLS) & Policies
-- ============================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ministries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pledges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access for users" ON public.users;
DROP POLICY IF EXISTS "Public access for organizations" ON public.organizations;
DROP POLICY IF EXISTS "Public access for members" ON public.members;
DROP POLICY IF EXISTS "Public access for ministries" ON public.ministries;
DROP POLICY IF EXISTS "Public access for pledges" ON public.pledges;

CREATE POLICY "Public access for users" ON public.users FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public access for organizations" ON public.organizations FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public access for members" ON public.members FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public access for ministries" ON public.ministries FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public access for pledges" ON public.pledges FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================================
-- Seed Initial Accounts & Default Organizations
-- ============================================================================

INSERT INTO public.users ("username", "password", "role")
VALUES 
    ('admin', 'admin', 'admin'),
    ('leader', 'leader', 'viewer')
ON CONFLICT ("username") DO NOTHING;

INSERT INTO public.organizations ("id", "name", "leaderId", "description")
VALUES 
    ('organization-1', 'Davao First Born Fellowship', '', 'Primary fellowship team based in Davao City.'),
    ('organization-2', 'Manila Assembly Organization', '', 'Metropolitan Manila FAFB LP cell organization.')
ON CONFLICT ("id") DO NOTHING;

-- Refresh Supabase Schema Cache
NOTIFY pgrst, 'reload schema';
